Chore workflow actions

diff --git a/.github/workflows/migrate.yml b/.github/workflows/migrate.yml
--- a/.github/workflows/migrate.yml
+++ b/.github/workflows/migrate.yml
@@ -1,42 +1,41 @@
 name: CI - Run Migrations
 
 on:
-  workflow_dispatch:
+    workflow_dispatch:
 
 jobs:
-  migrate:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: action
-      - name: Checkout migration folder
-        uses: appleboy/scp-action@master
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.ssh_user }}
-          key: ${{ secrets.SSH_KEY_PSQL }}
-          source: ./migrations
-          target: /home/ubuntu/
-      - name: Setup Docker compose
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USER }}
-          key: ${{ secrets.SSH_KEY_PSQL }}
-          script: |
-            cd /home/ubuntu/postgresql
-            docker compose up postgres-aus -d
-            sleep 10
-      - name: Apply migrations
-        run: |
-          cd /home/ubuntu/migrations
-          for migration in *.sql; do
-            echo "Applying migration: $migration"
-            docker compose exec -it postgres-aus psql -U aus-user -d aus -f $migration
-            if [ $? -ne 0 ]; then
-              echo "Error applying migration: $migration"
-              exit 1
-            fi
-          done
+    migrate:
+        runs-on: ubuntu-latest
 
-
+        steps:
+            - name: Checkout code
+              uses: actions/checkout@v3
+            - name: Checkout migration folder
+              uses: appleboy/scp-action@master
+              with:
+                  host: ${{ secrets.SSH_HOST }}
+                  username: ${{ secrets.ssh_user }}
+                  key: ${{ secrets.SSH_KEY_PSQL }}
+                  source: ./migrations
+                  target: /home/ubuntu/
+            - name: Setup Docker compose
+              uses: appleboy/ssh-action@master
+              with:
+                  host: ${{ secrets.SSH_HOST }}
+                  username: ${{ secrets.SSH_USER }}
+                  key: ${{ secrets.SSH_KEY_PSQL }}
+                  script: |
+                      cd /home/ubuntu/postgresql
+                      docker compose up postgres-aus -d
+                      sleep 10
+            - name: Apply migrations
+              run: |
+                  cd /home/ubuntu/migrations
+                  for migration in *.sql; do
+                    echo "Applying migration: $migration"
+                    docker compose exec -it postgres-aus psql -U aus-user -d aus -f $migration
+                    if [ $? -ne 0 ]; then
+                      echo "Error applying migration: $migration"
+                      exit 1
+                    fi
+                  done
